# Setup

title: Tem Plate   # put your name to replace "Tem Plate
description:  Law Student @ Birmingham Law School # you can change this line as well
tagline: 
baseurl: ""
locale: "en"

author: student name # your name
email: name@e.mail  # your email


show_downloads: false
google_analytics:
theme: jekyll-theme-architect

include:
    - _pages

  
# Gems
gems:
  - jekyll-paginate

  
# url
url: 'https://www.birmingham.ac.uk/schools/law/index.aspx' # you can change the url as well
  
#Others
markdown: kramdown
